"""Naukri scraper.

Naukri's job search runs through an internal API (jobapi/v3/search) that
requires a signed anti-bot header (`nkparam`) generated by their frontend
JS; calling it directly without that header gets a 400, and supplying the
other headers without a valid token gets a 406 "recaptcha required". Rather
than reverse-engineer or forge that token -- which would mean deliberately
defeating their bot detection -- this scraper drives a real, visible
browser to the search page and reads the JSON response the page's own
JavaScript legitimately requests. It's slower than the Greenhouse/Lever
scrapers and can't be run headless (headless browsing is one of the things
Naukri's detection looks for), but it never bypasses anything.

`target` is a search keyword (e.g. "java spring boot developer"), not a
company slug -- Naukri doesn't expose per-company boards like Greenhouse/Lever.
"""
import html
import re
from datetime import datetime

from playwright.sync_api import sync_playwright

from models.job import Job, Platform
from scrapers.base import JobScraper

BASE_URL = "https://www.naukri.com"
_TAG_RE = re.compile(r"<[^>]+>")


class NaukriScraper(JobScraper):
    def fetch_jobs(self, target: str) -> list[Job]:
        slug = "-".join(target.strip().lower().split())
        url = f"{BASE_URL}/{slug}-jobs"
        captured: dict = {}

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=False)
            page = browser.new_page()

            def handle_response(response):
                if "jobapi/v3/search" in response.url and response.ok:
                    try:
                        captured["data"] = response.json()
                    except Exception:  # noqa: BLE001 -- non-JSON responses just get skipped
                        pass

            page.on("response", handle_response)
            page.goto(url, timeout=30000)
            page.wait_for_timeout(4000)  # let the page's own API call land

            if "data" not in captured and "recaptcha" in page.content().lower():
                print(
                    f"Naukri is showing a captcha for '{target}'. Solve it in the "
                    "browser window that just opened, then re-run scrape."
                )
                page.wait_for_timeout(15000)

            browser.close()

        if "data" not in captured:
            return []

        jobs = []
        for item in captured["data"].get("jobDetails", []):
            placeholders = {p["type"]: p["label"] for p in item.get("placeholders", [])}
            jobs.append(
                Job(
                    external_id=str(item["jobId"]),
                    platform=Platform.NAUKRI,
                    company=item.get("companyName", "Unknown"),
                    title=item["title"],
                    location=placeholders.get("location"),
                    description=_strip_html(item.get("jobDescription", "")),
                    url=BASE_URL + item["jdURL"],
                    salary=placeholders.get("salary"),
                    posted_at=_parse_epoch_ms(item.get("createdDate")),
                )
            )
        return jobs


def _strip_html(text: str) -> str:
    return html.unescape(_TAG_RE.sub(" ", text)).strip()


def _parse_epoch_ms(value) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.utcfromtimestamp(int(value) / 1000)
    except (ValueError, TypeError, OverflowError):
        return None
